require "config.options"
require "config.plugins"
require "config.keymaps"
require "config.theme"
require "config.nvimtree"
require "config.telescope"
-- require "config.toggleterm"
require "config.treesitter"
require "config.autopairs"
require "config.lualine"
require "config.gitsigns"
require "config.harpoon"
require "config.comment"
require "config.cmp"
require "config.lsp"
require "config.trouble"

require "config.leetcode"
